websites = {
    "youtube": "https://www.youtube.com/",
    "chatgpt": "https://chat.openai.com/",
    "facebook": "https://www.facebook.com/",
    "instagram": "https://www.instagram.com/",
    "gmail": "https://mail.google.com/",
    "stackoverflow": "https://stackoverflow.com/",
    "github": "https://github.com/",
    "wikipedia": "https://www.wikipedia.org/",
    "google": "https://www.google.com/",
    "reddit": "https://www.reddit.com/",
    "linkedin": "https://www.linkedin.com/",
    "twitter": "https://twitter.com/",
    "netflix": "https://www.netflix.com/",
    "amazon": "https://www.amazon.com/",
    "spotify": "https://open.spotify.com/",
    "notion": "https://www.notion.so/",
    "canva": "https://www.canva.com/",
    "drive": "https://drive.google.com/",
    "zoom": "https://zoom.us/",
    "coursera": "https://www.coursera.org/",
    "udemy": "https://www.udemy.com/",
    "news": "https://www.bbc.com/news",
    "gemini": "https://gemini.google.com"
}
